services:
  comfyui:
    build: .
    ports:
      - "8188:8188"
    volumes:
      - /mnt/models/ComfyUI/models:/srv/app/models
      - /mnt/data/comfyui/input:/srv/app/input
      - /mnt/data/comfyui/output:/srv/app/output
      - /srv/comfyui/custom_nodes:/srv/app/custom_nodes
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2']
              capabilities: [gpu]
