services:
  comfyui:
    build: .
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - "8188:8188"
    environment:
      - HF_HOME=/srv/huggingface
    volumes:
      - /mnt/comfyui/models:/srv/app/models
      - /mnt/comfyui/huggingface_home:/srv/huggingface
      - /mnt/data/comfyui/input:/srv/app/input
      - /mnt/data/comfyui/output:/srv/app/output
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
