services:
  comfyui:
    build: .
    ports:
      - "8188:8188"
    volumes:
      - /srv/comfyui/models:/srv/app/models
      - /srv/comfyui/input:/srv/app/input
      - /srv/comfyui/output:/srv/app/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
